export interface modelDescriptionType {
  [key: string]: ImodelDescriptionType;
}
export interface ImodelDescriptionType {
  displayName: string;
  toolDisabled?: boolean;
  reasoningEffort?: reasoningEffortType[];
  vision?: boolean;
  fast?: boolean;
  defaultVisibility?: boolean;
  knowledgeCutoff?: string;
  reasoning?: boolean;
  type: modelType;
}

export type modelType = "ChatGPT" | "Gemini" | "Claude" | "Grok" | "DeepSeek";
export type reasoningEffortType = "low" | "medium" | "high";

// Powered by Voids.top (not used)
// export const modelDescriptions: modelDescriptionType = {
//   "gpt-4o-2024-11-20": {
//     displayName: "GPT-4o",
//     knowledgeCutoff: "2023/10",
//     defaultVisibility: true,
//     canary: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "gpt-4o-search-preview-2025-03-11": {
//     displayName: "GPT-4o Search Preview",
//     knowledgeCutoff: "2023/10",
//     offline: true,
//     toolDisabled: true,
//     canary: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "gpt-4o-mini-2024-07-18": {
//     displayName: "GPT-4o mini",
//     knowledgeCutoff: "2023/10",
//     defaultVisibility: true,
//     vision: true,
//     canary: true,
//     fast: true,
//     type: "ChatGPT",
//   },
//   "chatgpt-4o-latest": {
//     displayName: "ChatGPT-4o Latest",
//     knowledgeCutoff: "2023/10",
//     toolDisabled: true,
//     canary: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "o3-mini-2025-01-31": {
//     displayName: "o3-mini",
//     knowledgeCutoff: "2023/10",
//     reasoningEffort: ["low", "medium", "high"],
//     defaultVisibility: true,
//     reasoning: true,
//     canary: true,
//     type: "ChatGPT",
//   },
//   "o1-2024-12-17": {
//     displayName: "o1",
//     knowledgeCutoff: "2023/10",
//     reasoningEffort: ["low", "medium", "high"],
//     canary: true,
//     reasoning: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "o1-mini-2024-09-12": {
//     displayName: "o1-mini",
//     knowledgeCutoff: "2023/10",
//     reasoning: true,
//     canary: true,
//     type: "ChatGPT",
//   },
//   "gpt-4.5-preview-2025-02-27": {
//     displayName: "GPT-4.5 Preview",
//     knowledgeCutoff: "2023/10",
//     defaultVisibility: true,
//     canary: true,
//     reasoning: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "gpt-4-turbo-2024-04-09": {
//     displayName: "GPT-4 Turbo",
//     knowledgeCutoff: "2023/12",
//     canary: true,
//     vision: true,
//     type: "ChatGPT",
//   },
//   "gpt-4-0613": {
//     displayName: "GPT-4",
//     knowledgeCutoff: "2023/12",
//     canary: true,
//     type: "ChatGPT",
//   },
//   "gpt-3.5-turbo-0125": {
//     displayName: "GPT-3.5 Turbo",
//     knowledgeCutoff: "2022/01",
//     canary: true,
//     type: "ChatGPT",
//   },
//   "gemini-2.5-pro-exp-03-25": {
//     displayName: "Gemini 2.5 Pro",
//     knowledgeCutoff: "2025/01",
//     defaultVisibility: true,
//     vision: true,
//     canary: true,
//     type: "Gemini",
//   },
//   "gemini-2.0-pro-exp-02-05": {
//     displayName: "Gemini 2.0 Pro",
//     knowledgeCutoff: "-",
//     vision: true,
//     canary: true,
//     type: "Gemini",
//   },
//   "gemini-2.0-flash-001": {
//     displayName: "Gemini 2.0 Flash",
//     knowledgeCutoff: "2024/06",
//     defaultVisibility: true,
//     fast: true,
//     vision: true,
//     canary: true,
//     type: "Gemini",
//   },
//   "gemini-2.0-flash-thinking-exp-01-21": {
//     displayName: "Gemini 2.0 Flash Thinking",
//     knowledgeCutoff: "2024/06",
//     reasoning: true,
//     toolDisabled: true,
//     fast: true,
//     vision: true,
//     canary: true,
//     type: "Gemini",
//   },
//   "gemini-2.0-flash-lite-001": {
//     displayName: "Gemini 2.0 Flash Lite",
//     knowledgeCutoff: "2024/06",
//     fast: true,
//     vision: true,
//     canary: true,
//     type: "Gemini",
//   },
//   "gemini-1.5-pro": {
//     displayName: "Gemini 1.5 Pro",
//     knowledgeCutoff: "2023/11",
//     canary: true,
//     vision: true,
//     fast: true,
//     type: "Gemini",
//   },
//   "us.anthropic.claude-3-7-sonnet-20250219-v1:0": {
//     displayName: "Claude 3.7 Sonnet",
//     knowledgeCutoff: "2024/10",
//     defaultVisibility: true,
//     canary: true,
//     vision: true,
//     type: "Claude",
//   },
//   "us.anthropic.claude-3-7-sonnet-20250219-v1:0-reasoning": {
//     displayName: "Claude 3.7 Sonnet (Extended Thinking)",
//     knowledgeCutoff: "2024/10",
//     defaultVisibility: true,
//     toolDisabled: true,
//     canary: true,
//     vision: true,
//     type: "Claude",
//   },
//   "anthropic.claude-3-5-sonnet-20241022-v2:0": {
//     displayName: "Claude 3.5 Sonnet",
//     knowledgeCutoff: "2024/04",
//     canary: true,
//     vision: true,
//     type: "Claude",
//   },
//   "deepseek-r1-250120": {
//     displayName: "DeepSeek R1",
//     knowledgeCutoff: "2024/07",
//     reasoning: true,
//     toolDisabled: true,
//     canary: true,
//     type: "DeepSeek",
//   },
//   "deepseek-chat": {
//     displayName: "DeepSeek V3",
//     knowledgeCutoff: "2023/10",
//     fast: true,
//     canary: true,
//     toolDisabled: true,
//     type: "DeepSeek",
//   },
//   "grok-3": {
//     displayName: "Grok 3 Beta",
//     vision: true,
//     knowledgeCutoff: "-",
//     type: "Grok",
//   },
//   "grok-3-thinking": {
//     displayName: "Grok 3 (Think)",
//     knowledgeCutoff: "-",
//     reasoning: true,
//     type: "Grok",
//   },
// };

export const modelDescriptions: modelDescriptionType = {
  "openai/gpt-4.1-2025-04-14": {
    displayName: "GPT-4.1",
    knowledgeCutoff: "2024/06",
    defaultVisibility: true,
    vision: true,
    type: "ChatGPT",
  },
  "openai/gpt-4.1-mini-2025-04-14": {
    displayName: "GPT-4.1 mini",
    knowledgeCutoff: "2024/06",
    fast: true,
    vision: true,
    type: "ChatGPT",
  },
  "openai/gpt-4.1-nano-2025-04-14": {
    displayName: "GPT-4.1 nano",
    knowledgeCutoff: "2024/06",
    fast: true,
    vision: true,
    type: "ChatGPT",
  },
  "openai/gpt-4o-2024-11-20": {
    displayName: "GPT-4o",
    knowledgeCutoff: "2023/10",
    defaultVisibility: true,
    vision: true,
    type: "ChatGPT",
  },
  "openai/gpt-4o-mini-2024-07-18": {
    displayName: "GPT-4o mini",
    knowledgeCutoff: "2023/10",
    vision: true,
    fast: true,
    type: "ChatGPT",
  },
  "openai/o4-mini-2025-04-16": {
    displayName: "o4-mini",
    knowledgeCutoff: "2024/06",
    reasoningEffort: ["low", "medium", "high"],
    defaultVisibility: true,
    reasoning: true,
    vision: true,
    type: "ChatGPT",
  },
  "openai/o3-2025-04-16": {
    displayName: "o3",
    knowledgeCutoff: "2024/06",
    defaultVisibility: true,
    reasoningEffort: ["low", "medium", "high"],
    reasoning: true,
    vision: true,
    type: "ChatGPT",
  },
  "google/gemini-2.5-flash-preview-05-20": {
    displayName: "Gemini 2.5 Flash",
    knowledgeCutoff: "2025/01",
    fast: true,
    defaultVisibility: true,
    vision: true,
    type: "Gemini",
  },
  "google/gemini-2.5-pro-preview-05-06": {
    displayName: "Gemini 2.5 Pro",
    knowledgeCutoff: "2025/01",
    defaultVisibility: true,
    vision: true,
    type: "Gemini",
  },
  "google/gemini-2.0-flash-001": {
    displayName: "Gemini 2.0 Flash",
    knowledgeCutoff: "2024/06",
    fast: true,
    vision: true,
    type: "Gemini",
  },
  "anthropic/claude-3-7-sonnet-20250219": {
    displayName: "Claude 3.7 Sonnet",
    knowledgeCutoff: "2024/10",
    defaultVisibility: true,
    vision: true,
    type: "Claude",
  },
  "anthropic/claude-3-7-sonnet-20250219-reasoning": {
    displayName: "Claude 3.7 Sonnet (Reasoning)",
    knowledgeCutoff: "2024/10",
    defaultVisibility: true,
    vision: true,
    type: "Claude",
  },
  "groq/deepseek-r1-distill-llama-70b": {
    displayName: "DeepSeek R1 (Distill)",
    knowledgeCutoff: "2024/07",
    defaultVisibility: true,
    fast: true,
    reasoning: true,
    type: "DeepSeek",
  },
  "openrouter/deepseek/deepseek-chat": {
    displayName: "DeepSeek V3",
    knowledgeCutoff: "2023/10",
    fast: true,
    toolDisabled: true,
    type: "DeepSeek",
  },
  "xai/grok-3-beta": {
    displayName: "Grok 3 Beta",
    vision: true,
    defaultVisibility: true,
    type: "Grok",
  },
  "xai/grok-3-mini-beta": {
    displayName: "Grok 3 Mini Beta",
    vision: true,
    reasoning: true,
    type: "Grok",
  },
};
