import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight,
  BookOpenText,
  ClipboardCheck,
  Coins,
  GitBranch,
  GraduationCap,
  MessageSquareQuote,
  Shield,
  Sparkles,
} from "lucide-react";
import { useExtracted } from "next-intl";
import { getExtracted } from "next-intl/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getExtracted();
  const title = t("AI Guides");
  const description = t(
    "Practical guides for choosing AI models, verifying AI answers, multi-model workflows, prompt patterns, study habits, and privacy.",
  );

  return {
    title,
    description,
    alternates: {
      canonical: "https://deniai.app/guides",
    },
    openGraph: {
      title: `${title} — Deni AI`,
      description,
    },
    twitter: {
      title: `${title} | Deni AI`,
      description,
    },
  };
}

export default function GuidesPage() {
  const t = useExtracted();
  const headline = t("Practical AI guides for everyday decisions");
  const description = t(
    "These guides are written for people who use AI at work or in study and want clearer rules for model choice, verification, and responsible use. They are useful even before you create a Deni AI account.",
  );
  const guides = [
    {
      href: "/guides/model-selection",
      icon: Sparkles,
      title: t("How to choose an AI model for real work"),
      description: t(
        "A practical guide to choosing between fast, reasoning, coding, and writing-focused models without treating brand names as the decision.",
      ),
    },
    {
      href: "/guides/verify-ai-answers",
      icon: ClipboardCheck,
      title: t("How to verify AI answers before you rely on them"),
      description: t(
        "A review workflow for facts, numbers, code, citations, translations, and recommendations generated by AI assistants.",
      ),
    },
    {
      href: "/guides/multi-model-workflows",
      icon: GitBranch,
      title: t("When multi-model AI is actually useful"),
      description: t(
        "Concrete workflows for comparing models, reducing hallucination risk, improving drafts, and deciding when one answer is enough.",
      ),
    },
    {
      href: "/guides/prompt-patterns",
      icon: MessageSquareQuote,
      title: t("Prompt patterns that work across AI models"),
      description: t(
        "Reusable prompt skeletons for goals, constraints, structured output, and repair loops that transfer between providers.",
      ),
    },
    {
      href: "/guides/study-with-ai",
      icon: GraduationCap,
      title: t("How to study with AI without outsourcing your thinking"),
      description: t(
        "Study methods that use AI for explanation and practice while keeping retrieval, writing, and judgment with the learner.",
      ),
    },
    {
      href: "/guides/privacy-when-using-ai",
      icon: Shield,
      title: t("Privacy habits for everyday AI chat"),
      description: t(
        "What not to paste, how to redact sensitive material, and how to match tools to the real risk of the task.",
      ),
    },
    {
      href: "/guides/free-ai-chat",
      icon: Coins,
      title: t("How to choose a free AI chat workspace"),
      description: t(
        "A buyer-style checklist for free AI chat tools: limits, model flexibility, privacy pages, and when paid plans make sense.",
      ),
    },
  ];

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: headline,
    description,
    url: "https://deniai.app/guides",
    hasPart: guides.map((guide) => ({
      "@type": "Article",
      headline: guide.title,
      url: `https://deniai.app${guide.href}`,
    })),
  };

  return (
    <main className="min-h-screen bg-background" id="main-content">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }}
      />

      <section className="px-4 pb-16 pt-32 md:pb-20 md:pt-40">
        <div className="mx-auto max-w-5xl">
          <div className="max-w-3xl">
            <div className="mb-5 inline-flex size-11 items-center justify-center rounded-2xl bg-secondary">
              <BookOpenText className="size-5" />
            </div>
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-muted-foreground/70">
              {t("AI Guides")}
            </p>
            <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">
              {headline}
            </h1>
            <p className="mt-6 text-base leading-8 text-muted-foreground">{description}</p>
            <p className="mt-4 text-sm leading-7 text-muted-foreground">
              {t(
                "Each guide is original public writing from the Deni AI team. The goal is to help visitors make better decisions with any AI tool, then optionally use Deni AI when multi-model chat fits the work.",
              )}
            </p>
          </div>
        </div>
      </section>

      <section className="px-4 pb-20 md:pb-28">
        <div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-2 xl:grid-cols-3">
          {guides.map((guide) => {
            const Icon = guide.icon;

            return (
              <Link
                key={guide.href}
                href={guide.href}
                className="group rounded-[1.5rem] border border-border/70 bg-card p-6 transition-colors hover:border-foreground/30"
              >
                <div className="inline-flex size-11 items-center justify-center rounded-2xl bg-secondary">
                  <Icon className="size-5" />
                </div>
                <h2 className="mt-5 text-xl font-semibold tracking-tight">{guide.title}</h2>
                <p className="mt-3 text-sm leading-7 text-muted-foreground">{guide.description}</p>
                <span className="mt-6 inline-flex items-center gap-2 text-sm font-medium">
                  {t("Read guide")}
                  <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
                </span>
              </Link>
            );
          })}
        </div>
      </section>

      <section className="border-y border-border/50 bg-secondary/20 px-4 py-16 md:py-24">
        <div className="mx-auto max-w-4xl">
          <h2 className="text-2xl font-semibold tracking-tight">{t("Why these guides exist")}</h2>
          <div className="mt-5 space-y-4 text-sm leading-7 text-muted-foreground">
            <p>
              {t(
                "Many AI pages only list features. That is not enough when people need to decide which answer to trust, which model to use, or whether a task should involve AI at all.",
              )}
            </p>
            <p>
              {t(
                "The goal of this section is to make Deni AI useful as a public resource, not only as an app. Each guide gives concrete review steps, examples, and decision rules that visitors can apply in any AI workspace.",
              )}
            </p>
            <p>
              {t(
                "If you still have product questions after reading, visit the FAQ or contact page. If you are ready to try multi-model chat, open the workspace and start with a low-risk task.",
              )}
            </p>
          </div>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              href="/faq"
              className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2 text-sm font-medium hover:bg-secondary"
            >
              {t("FAQ")}
              <ArrowRight className="size-4" />
            </Link>
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2 text-sm font-medium hover:bg-secondary"
            >
              {t("Contact")}
              <ArrowRight className="size-4" />
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
